// ═══════════════════════════════════════════════════════════════════════════
// Hytale UI Builder - HYUIML Generator
// Generates HYUIML markup from design tree
// ═══════════════════════════════════════════════════════════════════════════

import type { UIElement, UIDesign, ElementProperties, Anchor, TextStyle } from '../types';
import { COMPONENT_DEFINITIONS } from '../defaults';

// ─── Generate HYUIML Code ───
export function generateHYUIMLCode(design: UIDesign): string {
  const lines: string[] = [];
  
  // Header comment
  lines.push('<!--');
  lines.push('  Generated by Hytale UI Builder (https://mytale.gg)');
  lines.push('  HYUIML is a conceptual HTML-like representation of Hytale UI.');
  lines.push('-->');
  lines.push('');
  
  // Generate root and children
  generateElementHYUIML(design.root, lines, 0, true);
  
  return lines.join('\n');
}

// ─── Generate Element ───
function generateElementHYUIML(element: UIElement, lines: string[], indent: number, isRoot: boolean = false): void {
  const prefix = '  '.repeat(indent);
  const definition = COMPONENT_DEFINITIONS[element.type];
  const tag = definition?.hyuimlTag || 'div';
  
  // Get clean element ID
  const elementId = getCleanId(element, isRoot);
  
  // Build attributes
  const attrs: string[] = [];
  attrs.push(`id="${elementId}"`);
  
  // Add data-type for clarity
  attrs.push(`data-type="${element.type}"`);
  
  // Style attribute
  const styleStr = generateStyleAttribute(element.properties);
  if (styleStr) {
    attrs.push(`style="${styleStr}"`);
  }
  
  // Type-specific attributes
  if (element.type === 'CheckBox' && 'checked' in element.properties) {
    attrs.push('type="checkbox"');
    if (element.properties.checked) {
      attrs.push('checked');
    }
  }
  
  if ((element.type === 'RawField' || element.type === 'TextInput' || element.type === 'NumberInput')) {
    if (element.type === 'NumberInput') {
      attrs.push('type="number"');
      if ('min' in element.properties && element.properties.min !== undefined) {
        attrs.push(`min="${element.properties.min}"`);
      }
      if ('max' in element.properties && element.properties.max !== undefined) {
        attrs.push(`max="${element.properties.max}"`);
      }
    } else {
      attrs.push('type="text"');
    }
    if ('placeholder' in element.properties && element.properties.placeholder) {
      attrs.push(`placeholder="${escapeHtml(element.properties.placeholder)}"`);
    }
    if ('value' in element.properties && element.properties.value !== undefined) {
      attrs.push(`value="${escapeHtml(element.properties.value)}"`);
    }
  }
  
  // Format attributes nicely
  const attrStr = formatAttributes(attrs, prefix, tag);
  
  // Special handling for different element types
  if (element.type === 'Label' || element.type === 'TimerLabel') {
    // Labels have text content
    const text = ('text' in element.properties && element.properties.text) || '';
    if (attrs.length <= 3) {
      lines.push(`${prefix}<${tag} ${attrs.join(' ')}>${escapeHtml(text)}</${tag}>`);
    } else {
      lines.push(`${prefix}<${tag}`);
      lines.push(attrStr);
      lines.push(`${prefix}>${escapeHtml(text)}</${tag}>`);
    }
  } else if (element.type === 'AssetImage') {
    // Images
    const assetPath = ('assetPath' in element.properties && element.properties.assetPath) || '';
    if (assetPath) {
      attrs.push(`src="${escapeHtml(assetPath)}"`);
    }
    lines.push(`${prefix}<img ${attrs.join(' ')} />`);
  } else if (element.type === 'RawButton' || element.type === 'TextButton' || 
             element.type === 'CancelButton' || element.type === 'BackButton') {
    // Buttons have text content
    const text = ('text' in element.properties && element.properties.text) || 'Button';
    if (attrs.length <= 3) {
      lines.push(`${prefix}<${tag} ${attrs.join(' ')}>${escapeHtml(text)}</${tag}>`);
    } else {
      lines.push(`${prefix}<${tag}`);
      lines.push(attrStr);
      lines.push(`${prefix}>${escapeHtml(text)}</${tag}>`);
    }
  } else if (element.type === 'RawField' || element.type === 'TextInput' || 
             element.type === 'NumberInput' || element.type === 'CheckBox') {
    // Self-closing input elements
    lines.push(`${prefix}<${tag} ${attrs.join(' ')} />`);
  } else if (element.type === 'ColorPicker') {
    lines.push(`${prefix}<input type="color" ${attrs.join(' ')} />`);
  } else {
    // Container elements (Group, etc.)
    if (element.children.length === 0) {
      lines.push(`${prefix}<${tag} ${attrs.join(' ')}></${tag}>`);
    } else {
      if (attrs.length <= 3) {
        lines.push(`${prefix}<${tag} ${attrs.join(' ')}>`);
      } else {
        lines.push(`${prefix}<${tag}`);
        lines.push(attrStr);
        lines.push(`${prefix}>`);
      }
      for (const child of element.children) {
        generateElementHYUIML(child, lines, indent + 1);
      }
      lines.push(`${prefix}</${tag}>`);
    }
  }
}

// ─── Get Clean Element ID ───
function getCleanId(element: UIElement, isRoot: boolean): string {
  if (isRoot) return 'root';
  
  // Use custom name if provided
  if (element.name && element.name !== element.type) {
    return sanitizeId(element.name);
  }
  
  // Otherwise use type + short hash
  return `${element.type.toLowerCase()}_${element.id.substring(0, 6)}`;
}

// ─── Sanitize ID ───
function sanitizeId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_-]/g, '_');
}

// ─── Format Attributes ───
function formatAttributes(attrs: string[], prefix: string, tag: string): string {
  const attrPrefix = prefix + '  ';
  return attrs.map(attr => `${attrPrefix}${attr}`).join('\n');
}

// ─── Generate Style Attribute ───
function generateStyleAttribute(props: ElementProperties): string {
  const styles: string[] = [];
  
  // Layout Mode
  if ('layoutMode' in props && props.layoutMode && props.layoutMode !== 'None') {
    const layoutMap: Record<string, string> = {
      'Top': 'display: flex; flex-direction: column; align-items: center; justify-content: flex-start',
      'Middle': 'display: flex; flex-direction: column; align-items: center; justify-content: center',
      'Bottom': 'display: flex; flex-direction: column; align-items: center; justify-content: flex-end',
      'MiddleCenter': 'display: flex; align-items: center; justify-content: center',
      'TopLeft': 'display: flex; align-items: flex-start; justify-content: flex-start',
      'TopRight': 'display: flex; align-items: flex-start; justify-content: flex-end',
      'BottomLeft': 'display: flex; align-items: flex-end; justify-content: flex-start',
      'BottomRight': 'display: flex; align-items: flex-end; justify-content: flex-end',
    };
    if (layoutMap[props.layoutMode]) {
      styles.push(layoutMap[props.layoutMode]);
    }
  }
  
  // Anchor dimensions
  if ('anchor' in props && props.anchor) {
    const anchor = props.anchor as Anchor;
    if (anchor.width !== undefined) styles.push(`width: ${anchor.width}px`);
    if (anchor.height !== undefined) styles.push(`height: ${anchor.height}px`);
    if (anchor.left !== undefined) styles.push(`left: ${anchor.left}px`);
    if (anchor.right !== undefined) styles.push(`right: ${anchor.right}px`);
    if (anchor.top !== undefined) styles.push(`top: ${anchor.top}px`);
    if (anchor.bottom !== undefined) styles.push(`bottom: ${anchor.bottom}px`);
    
    // Add position if any positional properties are set
    if (anchor.left !== undefined || anchor.right !== undefined || 
        anchor.top !== undefined || anchor.bottom !== undefined) {
      styles.unshift('position: absolute');
    }
  }
  
  // Background color
  if ('background' in props && props.background?.color && props.background.color !== 'transparent') {
    styles.push(`background-color: ${props.background.color}`);
  }
  
  // Text styling
  if ('style' in props && props.style) {
    const style = props.style as TextStyle;
    if (style.textColor) styles.push(`color: ${style.textColor}`);
    if (style.fontSize !== undefined) styles.push(`font-size: ${style.fontSize}px`);
    if (style.renderBold) styles.push(`font-weight: bold`);
    if (style.renderItalic) styles.push(`font-style: italic`);
  }
  
  // Alignment
  if ('alignment' in props && props.alignment) {
    const alignMap: Record<string, string> = {
      'Left': 'left',
      'Center': 'center',
      'Right': 'right',
    };
    styles.push(`text-align: ${alignMap[props.alignment] || 'left'}`);
  }
  
  // Padding
  if ('padding' in props && props.padding) {
    if (props.padding.all !== undefined) {
      styles.push(`padding: ${props.padding.all}px`);
    } else {
      const paddingParts: string[] = [];
      if (props.padding.top !== undefined) paddingParts.push(`padding-top: ${props.padding.top}px`);
      if (props.padding.right !== undefined) paddingParts.push(`padding-right: ${props.padding.right}px`);
      if (props.padding.bottom !== undefined) paddingParts.push(`padding-bottom: ${props.padding.bottom}px`);
      if (props.padding.left !== undefined) paddingParts.push(`padding-left: ${props.padding.left}px`);
      styles.push(...paddingParts);
    }
  }
  
  // Visibility
  if ('visible' in props && props.visible === false) {
    styles.push('display: none');
  }
  
  // Object fit for images
  if ('objectFit' in props && props.objectFit) {
    styles.push(`object-fit: ${props.objectFit}`);
  }
  
  return styles.join('; ');
}

// ─── Escape HTML ───
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
