// ═══════════════════════════════════════════════════════════════════════════
// Hytale UI Builder - HYUIML Generator
// Generates HYUIML markup from design tree
// ═══════════════════════════════════════════════════════════════════════════

import type { UIElement, UIDesign, ElementProperties, Anchor, TextStyle } from '../types';
import { COMPONENT_DEFINITIONS } from '../defaults';

// ─── Generate HYUIML Code ───
export function generateHYUIMLCode(design: UIDesign): string {
  const lines: string[] = [];
  
  // Header comment
  lines.push('<!-- Generated by Hytale UI Builder (https://mytale.gg) -->');
  
  // Generate root and children
  generateElementHYUIML(design.root, lines, 0);
  
  return lines.join('\n');
}

// ─── Generate Element ───
function generateElementHYUIML(element: UIElement, lines: string[], indent: number): void {
  const prefix = '  '.repeat(indent);
  const definition = COMPONENT_DEFINITIONS[element.type];
  const tag = definition?.hyuimlTag || 'div';
  
  // Build attributes
  const attrs: string[] = [];
  
  // ID
  if (element.name || element.id) {
    attrs.push(`id="${element.name || element.type}${element.id.substring(0, 8)}"`);
  }
  
  // Style attribute
  const styleStr = generateStyleAttribute(element.properties);
  if (styleStr) {
    attrs.push(`style="${styleStr}"`);
  }
  
  // Type-specific attributes
  if (element.type === 'CheckBox' && 'checked' in element.properties) {
    attrs.push('type="checkbox"');
    if (element.properties.checked) {
      attrs.push('checked');
    }
  }
  
  if ((element.type === 'RawField' || element.type === 'TextInput' || element.type === 'NumberInput')) {
    if (element.type === 'NumberInput') {
      attrs.push('type="number"');
    } else {
      attrs.push('type="text"');
    }
    if ('placeholder' in element.properties && element.properties.placeholder) {
      attrs.push(`placeholder="${escapeHtml(element.properties.placeholder)}"`);
    }
    if ('value' in element.properties && element.properties.value !== undefined) {
      attrs.push(`value="${escapeHtml(element.properties.value)}"`);
    }
  }
  
  const attrStr = attrs.length > 0 ? ' ' + attrs.join(' ') : '';
  
  // Special handling for different element types
  if (element.type === 'Label' || element.type === 'TimerLabel') {
    // Labels have text content
    const text = ('text' in element.properties && element.properties.text) || '';
    lines.push(`${prefix}<${tag}${attrStr}>${escapeHtml(text)}</${tag}>`);
  } else if (element.type === 'AssetImage') {
    // Images are self-closing with comment
    lines.push(`${prefix}<${tag}${attrStr}>`);
    lines.push(`${prefix}  <!-- Image is not supported yet in HYUIML. -->`);
    lines.push(`${prefix}</${tag}>`);
  } else if (element.type === 'RawButton' || element.type === 'TextButton' || 
             element.type === 'CancelButton' || element.type === 'BackButton') {
    // Buttons have text content
    const text = ('text' in element.properties && element.properties.text) || 'Button';
    lines.push(`${prefix}<${tag}${attrStr}>${escapeHtml(text)}</${tag}>`);
  } else if (element.type === 'RawField' || element.type === 'TextInput' || 
             element.type === 'NumberInput' || element.type === 'CheckBox') {
    // Self-closing input elements
    lines.push(`${prefix}<${tag}${attrStr} />`);
  } else if (element.type === 'ColorPicker') {
    lines.push(`${prefix}<${tag}${attrStr}>`);
    lines.push(`${prefix}  <!-- ColorPicker is not supported yet in HYUIML. -->`);
    lines.push(`${prefix}</${tag}>`);
  } else {
    // Container elements (Group, etc.)
    if (element.children.length === 0) {
      lines.push(`${prefix}<${tag}${attrStr}></${tag}>`);
    } else {
      lines.push(`${prefix}<${tag}${attrStr}>`);
      for (const child of element.children) {
        generateElementHYUIML(child, lines, indent + 1);
      }
      lines.push(`${prefix}</${tag}>`);
    }
  }
}

// ─── Generate Style Attribute ───
function generateStyleAttribute(props: ElementProperties): string {
  const styles: string[] = [];
  
  // Layout Mode
  if ('layoutMode' in props && props.layoutMode) {
    styles.push(`layout-mode: ${props.layoutMode.toLowerCase()}`);
  }
  
  // Anchor dimensions
  if ('anchor' in props && props.anchor) {
    const anchor = props.anchor as Anchor;
    if (anchor.width !== undefined) styles.push(`anchor-width: ${anchor.width}`);
    if (anchor.height !== undefined) styles.push(`anchor-height: ${anchor.height}`);
    if (anchor.left !== undefined) styles.push(`anchor-left: ${anchor.left}`);
    if (anchor.right !== undefined) styles.push(`anchor-right: ${anchor.right}`);
    if (anchor.top !== undefined) styles.push(`anchor-top: ${anchor.top}`);
    if (anchor.bottom !== undefined) styles.push(`anchor-bottom: ${anchor.bottom}`);
  }
  
  // Background color
  if ('background' in props && props.background?.color) {
    styles.push(`background-color: ${props.background.color}`);
  }
  
  // Text styling
  if ('style' in props && props.style) {
    const style = props.style as TextStyle;
    if (style.textColor) styles.push(`color: ${style.textColor}`);
    if (style.fontSize !== undefined) styles.push(`font-size: ${style.fontSize}`);
    if (style.renderBold) styles.push(`font-weight: bold`);
    if (style.renderItalic) styles.push(`font-style: italic`);
  }
  
  // Alignment
  if ('alignment' in props && props.alignment) {
    styles.push(`horizontal-align: ${props.alignment.toLowerCase()}`);
  }
  if ('verticalAlignment' in props && props.verticalAlignment) {
    styles.push(`vertical-align: ${props.verticalAlignment.toLowerCase()}`);
  }
  
  // Padding
  if ('padding' in props && props.padding) {
    if (props.padding.all !== undefined) {
      styles.push(`padding: ${props.padding.all}px`);
    } else {
      if (props.padding.top !== undefined) styles.push(`padding-top: ${props.padding.top}px`);
      if (props.padding.right !== undefined) styles.push(`padding-right: ${props.padding.right}px`);
      if (props.padding.bottom !== undefined) styles.push(`padding-bottom: ${props.padding.bottom}px`);
      if (props.padding.left !== undefined) styles.push(`padding-left: ${props.padding.left}px`);
    }
  }
  
  // Visibility
  if ('visible' in props && props.visible === false) {
    styles.push('display: none');
  }
  
  return styles.join('; ');
}

// ─── Escape HTML ───
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

