// ═══════════════════════════════════════════════════════════════════════════
// Hytale UI Builder - Java Code Generator
// Generates Java server code for Hytale mods from design tree
// ═══════════════════════════════════════════════════════════════════════════

import type { UIDesign, UIElement } from '../types';

// ─── Generate Java Code ───
export function generateJavaCode(design: UIDesign): string {
  const { packageName, className, uiFilePath } = design.settings;
  
  const lines: string[] = [];
  
  // Package declaration
  lines.push(`package ${packageName};`);
  lines.push('');
  
  // Imports
  lines.push('import com.hypixel.hytale.codec.Codec;');
  lines.push('import com.hypixel.hytale.codec.KeyedCodec;');
  lines.push('import com.hypixel.hytale.codec.builder.BuilderCodec;');
  lines.push('import com.hypixel.hytale.component.Ref;');
  lines.push('import com.hypixel.hytale.component.Store;');
  lines.push('import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;');
  lines.push('import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;');
  lines.push('import com.hypixel.hytale.server.core.Message;');
  lines.push('import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;');
  lines.push('import com.hypixel.hytale.server.core.ui.builder.EventData;');
  lines.push('import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;');
  lines.push('import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;');
  lines.push('import com.hypixel.hytale.server.core.universe.PlayerRef;');
  lines.push('import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;');
  lines.push('import javax.annotation.Nonnull;');
  lines.push('');
  
  // Class header comment
  lines.push('/**');
  lines.push(' * Generated by Hytale UI Builder (https://mytale.gg)');
  lines.push(' * You may edit this class as necessary, or copy parts only.');
  lines.push(' */');
  
  // Class declaration
  lines.push(`public class ${className} extends InteractiveCustomUIPage<${className}.BindingData> {`);
  lines.push('');
  
  // Constructor
  lines.push(`    public ${className}(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime) {`);
  lines.push('        super(playerRef, lifetime, BindingData.CODEC);');
  lines.push('    }');
  lines.push('');
  
  // Binding Data class
  lines.push('    /**');
  lines.push('     * Data class for UI bindings.');
  lines.push('     * Add fields here that need to be synced with the UI.');
  lines.push('     */');
  lines.push('    public static class BindingData {');
  lines.push('        public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)');
  
  // Generate binding fields from elements with bindings
  const bindingElements = collectBindingElements(design.root);
  
  if (bindingElements.length > 0) {
    for (const el of bindingElements) {
      const fieldName = sanitizeJavaIdentifier(el.name || el.type);
      lines.push(`            .with("${fieldName}", Codec.STRING, BindingData::get${capitalize(fieldName)}, BindingData::set${capitalize(fieldName)})`);
    }
  }
  
  lines.push('            .build();');
  lines.push('');
  
  // Generate fields for bindings
  if (bindingElements.length > 0) {
    for (const el of bindingElements) {
      const fieldName = sanitizeJavaIdentifier(el.name || el.type);
      lines.push(`        private String ${fieldName} = "";`);
    }
    lines.push('');
    
    // Generate getters and setters
    for (const el of bindingElements) {
      const fieldName = sanitizeJavaIdentifier(el.name || el.type);
      const capitalizedName = capitalize(fieldName);
      lines.push(`        public String get${capitalizedName}() { return ${fieldName}; }`);
      lines.push(`        public void set${capitalizedName}(String value) { this.${fieldName} = value; }`);
      lines.push('');
    }
  }
  
  lines.push('    }');
  lines.push('');
  
  // Build method
  lines.push('    @Override');
  lines.push('    public void build(');
  lines.push('            @Nonnull Ref<EntityStore> ref,');
  lines.push('            @Nonnull UICommandBuilder uiCommandBuilder,');
  lines.push('            @Nonnull UIEventBuilder uiEventBuilder,');
  lines.push('            @Nonnull Store<EntityStore> store) {');
  lines.push('');
  lines.push(`        uiCommandBuilder.append("${uiFilePath}");`);
  lines.push('');
  
  // Generate event bindings for buttons and interactive elements
  const interactiveElements = collectInteractiveElements(design.root);
  
  if (interactiveElements.length > 0) {
    lines.push('        // Event bindings');
    for (const el of interactiveElements) {
      const elementId = getCleanId(el);
      const handlerName = `on${capitalize(sanitizeJavaIdentifier(el.name || el.type))}Click`;
      lines.push(`        uiEventBuilder.bind("#${elementId}", CustomUIEventBindingType.ON_CLICK, this::${handlerName});`);
    }
    lines.push('');
  }
  
  lines.push('    }');
  lines.push('');
  
  // Generate event handler methods
  if (interactiveElements.length > 0) {
    lines.push('    // ─── Event Handlers ───');
    lines.push('');
    
    for (const el of interactiveElements) {
      const handlerName = `on${capitalize(sanitizeJavaIdentifier(el.name || el.type))}Click`;
      const elementName = el.name || el.type;
      lines.push(`    private void ${handlerName}(EventData data) {`);
      lines.push(`        // Handle ${elementName} click event`);
      lines.push('        // Example: this.close();');
      lines.push('    }');
      lines.push('');
    }
  }
  
  // Close class
  lines.push('}');
  
  return lines.join('\n');
}

// ─── Get Clean Element ID ───
function getCleanId(element: UIElement): string {
  // Use custom name if provided
  if (element.name && element.name !== element.type) {
    return sanitizeId(element.name);
  }
  
  // Otherwise use type + short hash
  return `${element.type}_${element.id.substring(0, 6)}`;
}

// ─── Sanitize ID ───
function sanitizeId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// ─── Collect Elements with Bindings ───
function collectBindingElements(element: UIElement): UIElement[] {
  const result: UIElement[] = [];
  
  if ('binding' in element.properties && element.properties.binding?.enabled) {
    result.push(element);
  }
  
  for (const child of element.children) {
    result.push(...collectBindingElements(child));
  }
  
  return result;
}

// ─── Collect Interactive Elements ───
function collectInteractiveElements(element: UIElement): UIElement[] {
  const result: UIElement[] = [];
  
  const interactiveTypes = [
    'RawButton',
    'TextButton',
    'CancelButton',
    'BackButton',
    'CheckBox',
  ];
  
  if (interactiveTypes.includes(element.type)) {
    result.push(element);
  }
  
  for (const child of element.children) {
    result.push(...collectInteractiveElements(child));
  }
  
  return result;
}

// ─── Sanitize Java Identifier ───
function sanitizeJavaIdentifier(name: string): string {
  // Remove non-alphanumeric characters and ensure it starts with a letter
  let sanitized = name.replace(/[^a-zA-Z0-9]/g, '');
  if (sanitized.length === 0 || /^[0-9]/.test(sanitized)) {
    sanitized = 'element' + sanitized;
  }
  // Convert to camelCase
  return sanitized.charAt(0).toLowerCase() + sanitized.slice(1);
}

// ─── Capitalize ───
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
