// ═══════════════════════════════════════════════════════════════════════════
// Hytale UI Builder - Java Code Generator
// Generates production-ready Java server code for Hytale mods
// Based on Hytale's UI system documentation
// ═══════════════════════════════════════════════════════════════════════════

import type { UIDesign, UIElement, Binding } from '../types';

// ─── Generate Java Code ───
export function generateJavaCode(design: UIDesign): string {
  const { settings } = design;
  const isInteractive = settings.pageType === 'InteractiveCustomUIPage' || hasEventBindings(design.root);
  const isHud = settings.pageType === 'CustomUIHud';
  
  if (isHud) {
    return generateHudClass(design);
  } else if (isInteractive) {
    return generateInteractivePageClass(design);
  } else {
    return generateSimplePageClass(design);
  }
}

// ─── Check if design has event bindings ───
function hasEventBindings(element: UIElement): boolean {
  const props = element.properties;
  if ('binding' in props && props.binding?.enabled) return true;
  return element.children.some(hasEventBindings);
}

// ─── Collect elements with IDs (for selectors) ───
function collectNamedElements(element: UIElement, path: string = ''): { id: string; name: string; type: string; path: string }[] {
  const results: { id: string; name: string; type: string; path: string }[] = [];
  
  if (element.name) {
    const currentPath = path ? `${path} #${element.name}` : `#${element.name}`;
    results.push({
      id: element.id,
      name: element.name,
      type: element.type,
      path: currentPath,
    });
    
    for (const child of element.children) {
      results.push(...collectNamedElements(child, currentPath));
    }
  } else {
    for (const child of element.children) {
      results.push(...collectNamedElements(child, path));
    }
  }
  
  return results;
}

// ─── Generate Simple CustomUIPage ───
function generateSimplePageClass(design: UIDesign): string {
  const { settings } = design;
  const namedElements = collectNamedElements(design.root);
  
  return `package ${settings.packageName};

import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.server.core.entity.entities.player.pages.CustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import javax.annotation.Nonnull;

/**
 * ${design.name}
 * ${design.description || 'Generated by Hytale UI Builder (https://mytale.gg)'}
 * 
 * UI Template: ${settings.uiFilePath}
 */
public class ${settings.className} extends CustomUIPage {

    public ${settings.className}(@Nonnull PlayerRef playerRef) {
        super(playerRef, CustomPageLifetime.${settings.pageLifetime});
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref,
                      @Nonnull UICommandBuilder ui,
                      @Nonnull UIEventBuilder events,
                      @Nonnull Store<EntityStore> store) {

        // Load the main page template
        ui.append("${settings.uiFilePath}");

${generateSelectorComments(namedElements)}
    }
}

${generateOpenPageHelper(settings)}
`;
}

// ─── Generate InteractiveCustomUIPage ───
function generateInteractivePageClass(design: UIDesign): string {
  const { settings } = design;
  const namedElements = collectNamedElements(design.root);
  const bindingElements = collectBindingElements(design.root);
  
  return `package ${settings.packageName};

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import javax.annotation.Nonnull;

/**
 * ${design.name}
 * ${design.description || 'Generated by Hytale UI Builder (https://mytale.gg)'}
 * 
 * UI Template: ${settings.uiFilePath}
 * Type: Interactive Page with event handling
 */
public class ${settings.className} extends InteractiveCustomUIPage<${settings.className}.EventPayload> {

    public ${settings.className}(@Nonnull PlayerRef playerRef) {
        super(playerRef, CustomPageLifetime.${settings.pageLifetime}, EventPayload.CODEC);
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref,
                      @Nonnull UICommandBuilder ui,
                      @Nonnull UIEventBuilder events,
                      @Nonnull Store<EntityStore> store) {

        // Load the main page template
        ui.append("${settings.uiFilePath}");

${generateEventBindings(bindingElements)}
${generateSelectorComments(namedElements)}
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref,
                                @Nonnull Store<EntityStore> store,
                                @Nonnull EventPayload data) {
        switch (data.action) {
${generateEventHandlers(bindingElements)}
            default:
                System.out.println("Unknown action: " + data.action);
                break;
        }
    }

    /**
     * Event payload for UI interactions
     */
    public static class EventPayload {
        public static final BuilderCodec<EventPayload> CODEC = BuilderCodec.builder(EventPayload.class, EventPayload::new)
            .with("action", Codec.STRING, e -> e.action, (e, v) -> e.action = v)
            .with("elementId", Codec.STRING, e -> e.elementId, (e, v) -> e.elementId = v)
            .with("value", Codec.STRING, e -> e.value, (e, v) -> e.value = v)
            .build();

        private String action = "";
        private String elementId = "";
        private String value = "";

        public String getAction() { return action; }
        public String getElementId() { return elementId; }
        public String getValue() { return value; }
    }
}

${generateOpenPageHelper(settings)}
`;
}

// ─── Generate CustomUIHud ───
function generateHudClass(design: UIDesign): string {
  const { settings } = design;
  const namedElements = collectNamedElements(design.root);
  
  return `package ${settings.packageName};

import com.hypixel.hytale.server.core.entity.entities.player.huds.CustomUIHud;
import com.hypixel.hytale.server.core.ui.builder.AnchorBuilder;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;

import javax.annotation.Nonnull;

/**
 * ${design.name}
 * ${design.description || 'Generated by Hytale UI Builder (https://mytale.gg)'}
 * 
 * UI Template: ${settings.uiFilePath}
 * Type: Custom HUD (always-visible overlay)
 */
public class ${settings.className} extends CustomUIHud {

    // HUD data fields - update these to change what's displayed
    private String mainText = "";
    private String subText = "";
    private boolean visible = true;

    public ${settings.className}(@Nonnull PlayerRef playerRef) {
        super(playerRef);
    }

    /**
     * Update the HUD content
     */
    public void updateData(String mainText, String subText) {
        this.mainText = mainText;
        this.subText = subText;
    }

    /**
     * Show or hide the HUD
     */
    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    @Override
    protected void build(@Nonnull UICommandBuilder ui) {
        if (!visible || mainText.isEmpty()) {
            return;
        }

        // Load the HUD template
        ui.append("Hud/${extractFileName(settings.uiFilePath)}");

        // Position the HUD (top-left corner, 20px from edges)
        AnchorBuilder anchor = new AnchorBuilder()
            .setTop(20)
            .setLeft(20);

        ui.setObject("#${design.root.name || 'HUD'}.Anchor", anchor.build());

${generateHudSetters(namedElements)}
    }
}

/**
 * HUD System - Call this in your entity ticking system to update the HUD
 * 
 * Example usage:
 * 
 * public class ${settings.className}System extends EntityTickingSystem<EntityStore> {
 *     private final Map<UUID, ${settings.className}> huds = new HashMap<>();
 *
 *     @Override
 *     public void tick(float dt, int index, ArchetypeChunk<EntityStore> chunk,
 *                     Store<EntityStore> store, CommandBuffer<EntityStore> buffer) {
 *
 *         PlayerRef playerRef = chunk.getComponent(index, PlayerRef.getComponentType());
 *         Player player = chunk.getComponent(index, Player.getComponentType());
 *
 *         if (playerRef == null || player == null) return;
 *
 *         ${settings.className} hud = huds.computeIfAbsent(playerRef.getUuid(), uuid -> {
 *             return new ${settings.className}(playerRef);
 *         });
 *
 *         // Update HUD data
 *         hud.updateData("Your Text Here", "Subtitle");
 *
 *         // Show the HUD
 *         player.getHudManager().setCustomHud(playerRef, hud);
 *     }
 *
 *     @Override
 *     public Query<EntityStore> getQuery() {
 *         return Query.and(Player.getComponentType());
 *     }
 * }
 */
`;
}

// ─── Helper Functions ───

function extractFileName(path: string): string {
  const parts = path.split('/');
  return parts[parts.length - 1];
}

function collectBindingElements(element: UIElement): { name: string; type: string; binding: Binding }[] {
  const results: { name: string; type: string; binding: Binding }[] = [];
  
  if (element.name) {
    const props = element.properties;
    if ('binding' in props && props.binding?.enabled) {
      results.push({
        name: element.name,
        type: element.type,
        binding: props.binding,
      });
    }
  }
  
  for (const child of element.children) {
    results.push(...collectBindingElements(child));
  }
  
  return results;
}

function generateEventBindings(elements: { name: string; type: string; binding: Binding }[]): string {
  if (elements.length === 0) {
    return `        // Add event bindings here
        // Example:
        // events.addEventBinding(
        //     CustomUIEventBindingType.Activating,  // Click event
        //     "#MyButton",                          // Element selector
        //     EventData.of("action", "buttonClick"),// Data to send
        //     false                                 // Not buffered
        // );`;
  }
  
  const lines: string[] = ['        // Event bindings'];
  for (const el of elements) {
    const eventType = el.binding.eventType || 'Activating';
    const actionName = el.binding.eventHandler || `on${el.name}Click`;
    lines.push(`        events.addEventBinding(`);
    lines.push(`            CustomUIEventBindingType.${eventType},`);
    lines.push(`            "#${el.name}",`);
    lines.push(`            EventData.of("action", "${actionName}").append("elementId", "${el.name}"),`);
    lines.push(`            false`);
    lines.push(`        );`);
    lines.push('');
  }
  
  return lines.join('\n');
}

function generateEventHandlers(elements: { name: string; type: string; binding: Binding }[]): string {
  if (elements.length === 0) {
    return `            case "exampleAction":
                // Handle example action
                break;`;
  }
  
  const lines: string[] = [];
  for (const el of elements) {
    const actionName = el.binding.eventHandler || `on${el.name}Click`;
    lines.push(`            case "${actionName}":`);
    lines.push(`                // Handle ${el.name} ${el.binding.eventType || 'click'}`);
    lines.push(`                System.out.println("${el.name} activated");`);
    lines.push(`                break;`);
  }
  
  return lines.join('\n');
}

function generateSelectorComments(elements: { name: string; type: string; path: string }[]): string {
  if (elements.length === 0) return '';
  
  const lines: string[] = [
    '        // ─── Available Selectors ───',
    '        // Use these selectors with ui.set() to update element properties:',
  ];
  
  for (const el of elements) {
    let props = '';
    switch (el.type) {
      case 'Label':
      case 'Title':
        props = '.Text, .Visible';
        break;
      case 'ItemIcon':
        props = '.ItemId, .Visible';
        break;
      case 'ProgressBar':
        props = '.Value';
        break;
      case 'AssetImage':
        props = '.Asset, .Visible';
        break;
      default:
        props = '.Visible';
    }
    lines.push(`        // ui.set("${el.path}${props}", value);`);
  }
  
  return lines.join('\n');
}

function generateHudSetters(elements: { name: string; type: string; path: string }[]): string {
  const lines: string[] = ['        // Set HUD content'];
  
  for (const el of elements) {
    if (el.type === 'Label') {
      if (el.name.toLowerCase().includes('main') || el.name.toLowerCase().includes('title')) {
        lines.push(`        ui.set("${el.path}.Text", mainText);`);
      } else if (el.name.toLowerCase().includes('sub')) {
        lines.push(`        ui.set("${el.path}.Text", subText);`);
      }
    }
  }
  
  if (lines.length === 1) {
    lines.push(`        // ui.set("#MainText.Text", mainText);`);
    lines.push(`        // ui.set("#SubText.Text", subText);`);
  }
  
  return lines.join('\n');
}

function generateOpenPageHelper(settings: { packageName: string; className: string }): string {
  return `/*
 * ═══════════════════════════════════════════════════════════════════════════
 * HOW TO OPEN THIS PAGE
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * From a command or event handler:
 *
 * world.execute(() -> {
 *     Player player = store.getComponent(ref, Player.getComponentType());
 *     PlayerRef playerRef = store.getComponent(ref, PlayerRef.getComponentType());
 *
 *     if (player != null && playerRef != null) {
 *         ${settings.className} page = new ${settings.className}(playerRef);
 *         player.getPageManager().openCustomPage(ref, store, page);
 *     }
 * });
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * FILE STRUCTURE
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * src/main/resources/
 * ├── manifest.json              <- Add: "IncludesAssetPack": true
 * └── Common/
 *     └── UI/
 *         └── Custom/
 *             └── Pages/
 *                 └── ${settings.className}.ui
 *
 * ═══════════════════════════════════════════════════════════════════════════
 */`;
}
