// ═══════════════════════════════════════════════════════════════════════════
// Hytale UI Builder - .ui Format Generator
// Generates Hytale .ui format code from design tree
// ═══════════════════════════════════════════════════════════════════════════

import type { UIElement, UIDesign, ElementProperties, Anchor, Padding, TextStyle } from '../types';
import { COMPONENT_DEFINITIONS } from '../defaults';

// ─── Generate .ui Code ───
export function generateUICode(design: UIDesign): string {
  const lines: string[] = [];
  
  // Header comment
  lines.push('// Generated by Hytale UI Builder (https://mytale.gg).');
  lines.push(`$C = "${design.settings.commonUiPath}";`);
  lines.push('');
  
  // Generate root and children
  generateElementUI(design.root, lines, 0);
  
  return lines.join('\n');
}

// ─── Generate Element ───
function generateElementUI(element: UIElement, lines: string[], indent: number): void {
  const prefix = '  '.repeat(indent);
  const definition = COMPONENT_DEFINITIONS[element.type];
  const uiKeyword = definition?.uiKeyword || element.type;
  
  // Element header with ID
  const idPart = element.id ? ` #${element.name || element.type}${element.id.substring(0, 8)}` : '';
  lines.push(`${prefix}${uiKeyword}${idPart} {`);
  
  // Generate properties
  generatePropertiesUI(element.properties, lines, indent + 1);
  
  // Generate children
  for (const child of element.children) {
    generateElementUI(child, lines, indent + 1);
  }
  
  lines.push(`${prefix}}`);
}

// ─── Generate Properties ───
function generatePropertiesUI(props: ElementProperties, lines: string[], indent: number): void {
  const prefix = '  '.repeat(indent);
  
  // Layout Mode
  if ('layoutMode' in props && props.layoutMode) {
    lines.push(`${prefix}LayoutMode: ${props.layoutMode};`);
  }
  
  // Background
  if ('background' in props && props.background) {
    if (props.background.color) {
      lines.push(`${prefix}Background: ${props.background.color};`);
    } else if (props.background.image) {
      lines.push(`${prefix}Background: (Image: "${props.background.image}");`);
    }
  }
  
  // Anchor
  if ('anchor' in props && props.anchor) {
    const anchorStr = formatAnchor(props.anchor);
    if (anchorStr) {
      lines.push(`${prefix}Anchor: ${anchorStr};`);
    }
  }
  
  // Padding
  if ('padding' in props && props.padding) {
    const paddingStr = formatPadding(props.padding);
    if (paddingStr) {
      lines.push(`${prefix}Padding: ${paddingStr};`);
    }
  }
  
  // Alignment (for labels)
  if ('alignment' in props && props.alignment) {
    lines.push(`${prefix}Alignment: ${props.alignment};`);
  }
  
  // Style (for labels and text elements)
  if ('style' in props && props.style) {
    const styleStr = formatTextStyle(props.style);
    if (styleStr) {
      lines.push(`${prefix}Style: ${styleStr};`);
    }
  }
  
  // Text
  if ('text' in props && props.text !== undefined) {
    lines.push(`${prefix}Text: "${escapeString(props.text)}";`);
  }
  
  // Placeholder
  if ('placeholder' in props && props.placeholder) {
    lines.push(`${prefix}Placeholder: "${escapeString(props.placeholder)}";`);
  }
  
  // Value
  if ('value' in props && props.value !== undefined) {
    lines.push(`${prefix}Value: "${escapeString(props.value)}";`);
  }
  
  // Asset Path (for images)
  if ('assetPath' in props && props.assetPath) {
    lines.push(`${prefix}Asset: "${props.assetPath}";`);
  }
  
  // Visible
  if ('visible' in props && props.visible === false) {
    lines.push(`${prefix}Visible: false;`);
  }
  
  // Flex Weight
  if ('flexWeight' in props && props.flexWeight !== undefined) {
    lines.push(`${prefix}FlexWeight: ${props.flexWeight};`);
  }
  
  // Scroll Style
  if ('scrollStyle' in props && props.scrollStyle) {
    lines.push(`${prefix}ScrollStyle: ${props.scrollStyle};`);
  }
  
  // Macro reference
  if ('macro' in props && props.macro) {
    lines.push(`${prefix}${props.macro};`);
  }
  
  // Fill Constraints
  if ('fillConstraints' in props && props.fillConstraints) {
    if (props.fillConstraints.full) {
      lines.push(`${prefix}Fill: ${props.fillConstraints.full};`);
    }
    if (props.fillConstraints.horizontal) {
      lines.push(`${prefix}FillHorizontal: ${props.fillConstraints.horizontal};`);
    }
    if (props.fillConstraints.vertical) {
      lines.push(`${prefix}FillVertical: ${props.fillConstraints.vertical};`);
    }
  }
  
  // Checked (for checkboxes)
  if ('checked' in props && props.checked !== undefined) {
    lines.push(`${prefix}Checked: ${props.checked};`);
  }
  
  // Label (for checkboxes)
  if ('label' in props && props.label) {
    lines.push(`${prefix}Label: "${escapeString(props.label)}";`);
  }
  
  // Min/Max (for number inputs)
  if ('min' in props && props.min !== undefined) {
    lines.push(`${prefix}Min: ${props.min};`);
  }
  if ('max' in props && props.max !== undefined) {
    lines.push(`${prefix}Max: ${props.max};`);
  }
}

// ─── Format Anchor ───
function formatAnchor(anchor: Anchor): string {
  const parts: string[] = [];
  
  if (anchor.width !== undefined) parts.push(`Width: ${anchor.width}`);
  if (anchor.height !== undefined) parts.push(`Height: ${anchor.height}`);
  if (anchor.left !== undefined) parts.push(`Left: ${anchor.left}`);
  if (anchor.right !== undefined) parts.push(`Right: ${anchor.right}`);
  if (anchor.top !== undefined) parts.push(`Top: ${anchor.top}`);
  if (anchor.bottom !== undefined) parts.push(`Bottom: ${anchor.bottom}`);
  if (anchor.minWidth !== undefined) parts.push(`MinWidth: ${anchor.minWidth}`);
  if (anchor.maxWidth !== undefined) parts.push(`MaxWidth: ${anchor.maxWidth}`);
  if (anchor.minHeight !== undefined) parts.push(`MinHeight: ${anchor.minHeight}`);
  if (anchor.maxHeight !== undefined) parts.push(`MaxHeight: ${anchor.maxHeight}`);
  
  if (parts.length === 0) return '';
  return `(${parts.join(', ')})`;
}

// ─── Format Padding ───
function formatPadding(padding: Padding): string {
  const parts: string[] = [];
  
  if (padding.all !== undefined) {
    return `${padding.all}`;
  }
  
  if (padding.top !== undefined) parts.push(`Top: ${padding.top}`);
  if (padding.right !== undefined) parts.push(`Right: ${padding.right}`);
  if (padding.bottom !== undefined) parts.push(`Bottom: ${padding.bottom}`);
  if (padding.left !== undefined) parts.push(`Left: ${padding.left}`);
  if (padding.horizontal !== undefined) parts.push(`Horiz: ${padding.horizontal}`);
  
  if (parts.length === 0) return '';
  return `(${parts.join(', ')})`;
}

// ─── Format Text Style ───
function formatTextStyle(style: TextStyle): string {
  const parts: string[] = [];
  
  if (style.textColor) parts.push(`TextColor: ${style.textColor}`);
  if (style.fontSize !== undefined) parts.push(`FontSize: ${style.fontSize}`);
  if (style.renderBold) parts.push(`RenderBold: true`);
  if (style.renderItalic) parts.push(`RenderItalic: true`);
  if (style.fontFamily) parts.push(`FontFamily: "${style.fontFamily}"`);
  
  if (parts.length === 0) return '';
  return `(${parts.join(', ')})`;
}

// ─── Escape String ───
function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

